language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - '7.1.0alpha1'
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: '7.1.0alpha1'
    - php: hhvm
  include:
    - php: 5.6
      env: XDEBUG_OFF="yes"
    - php: 7.0
      env: XDEBUG_OFF="yes"

script:
  - php -S localhost -t ./tests/fixtures/http-root
  - curl -S http://localhost
  - composer require jbzoo/http-client --no-update
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "5.3" ]; then composer require guzzlehttp/guzzle --no-update;  fi;'
  - make
  - make server
  - curl -S http://127.0.0.1:8081
  - curl -S http://127.0.0.1:8081?test=57a269bfa7025
  - make test-all
  - curl -S http://127.0.0.1:8081?test=12321321

after_script:
 - make coveralls
