language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - '7.1.0alpha1'
  - hhvm

matrix:
  fast_finish: true

script:
  - chmod +x ./webserver.sh
  - ./web-root/webserver.sh
  - curl -S http://localhost:8888
  - exit 0
