language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true

before_script:
  - composer self-update
  - composer update;
  - phpenv rehash

script:
  - composer test;

after_script:
 - php vendor/bin/coveralls --verbose
