#
# JBZoo Toolbox - PHPUnit
#
# This file is part of the JBZoo Toolbox project.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @package    PHPUnit
# @license    MIT
# @copyright  Copyright (C) JBZoo.com, All rights reserved.
# @link       https://github.com/JBZoo/PHPUnit
#

language: php

php:
  - 7.2
  - 7.3
  - 7.4

matrix:
  fast_finish: true
  include:
    - php: 7.4
      env: XDEBUG_OFF="yes"

script:
  - if [[ $XDEBUG_OFF = yes ]]; then phpenv config-rm xdebug.ini; fi;
  - make update
  - make server
  - make test-all

after_script:
 - make report-coveralls
